### ISSUE TITLE
Warsztaty z Git + Bash - lista obecności

### ISSUE THREAD

**Issue by smudap** [Kolo-Naukowe-Data-Science-PW/warsztaty#6]
Prosimy o wpisanie się na listę obecności:
https://docs.google.com/forms/d/e/1FAIpQLSca_j5nBO1k448teDZF5X0fei7DaGlQGsj31-nsdoxzIWKH7g/viewform?c=0&w=1

**Comment by SylwiaKolodziejska** [comment]
Sylwia Kołodziejska
